[project]
name = "worldquant"
version = "0.1.0"
description = "worldquant api"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["requests"]

[project.optional-dependencies]
dev = ["python-lsp-server", "python-lsp-ruff"]
